"""CVLN Academy API — one router per domain, aggregated here."""

from __future__ import annotations

from fastapi import APIRouter

from . import (
    accounting,
    assistants,
    assurance,
    auth,
    authority_policy,
    badges,
    canonical,
    certification,
    commerce,
    data_classification,
    ecosystem_builder,
    evidence_graph,
    expert_portal,
    fms,
    fms_lineage,
    formations,
    frk_canonical,
    health,
    incident_core,
    integrations,
    klt_canonical,
    kor_canonical,
    learning,
    legal_clauses,
    legal_documents,
    legal_ops,
    legal_policy,
    mentor,
    missions,
    onboarding,
    orgs,
    payments,
    physical_sessions,
    policy_registry,
    privacy_ops,
    professional_governance,
    professional_profile,
    progression,
    quality,
    quizzes,
    qualification,
    retention_executor,
    security_remediation,
    skills,
    templates,
    threat_model,
    wallet,
)

router = APIRouter(prefix="/api")

for module in (
    health,
    auth,
    onboarding,
    orgs,
    formations,
    learning,
    quizzes,
    badges,
    missions,
    progression,
    mentor,
    fms,
    fms_lineage,
    canonical,
    klt_canonical,
    kor_canonical,
    frk_canonical,
    skills,
    certification,
    qualification,
    physical_sessions,
    templates,
    assistants,
    wallet,
    integrations,
    commerce,
    payments,
    accounting,
    professional_governance,
    authority_policy,
    policy_registry,
    data_classification,
    retention_executor,
    evidence_graph,
    incident_core,
    expert_portal,
    assurance,
    legal_ops,
    legal_policy,
    legal_documents,
    legal_clauses,
    privacy_ops,
    quality,
    threat_model,
    security_remediation,
    professional_profile,
    ecosystem_builder,
):
    router.include_router(module.router)
