"""CVLN Academy API — one router per domain, aggregated here."""

from __future__ import annotations

from fastapi import APIRouter

from . import (
    accounting,
    assistants,
    assurance,
    auth,
    badges,
    canonical,
    certification,
    commerce,
    ecosystem_builder,
    expert_portal,
    fms,
    fms_lineage,
    formations,
    frk_canonical,
    health,
    integrations,
    klt_canonical,
    kor_canonical,
    learning,
    mentor,
    missions,
    onboarding,
    orgs,
    payments,
    physical_sessions,
    privacy_ops,
    professional_governance,
    professional_profile,
    progression,
    quality,
    quizzes,
    qualification,
    skills,
    templates,
    threat_model,
    wallet,
)

router = APIRouter(prefix="/api")

for module in (
    health,
    auth,
    onboarding,
    orgs,
    formations,
    learning,
    quizzes,
    badges,
    missions,
    progression,
    mentor,
    fms,
    fms_lineage,
    canonical,
    klt_canonical,
    kor_canonical,
    frk_canonical,
    skills,
    certification,
    qualification,
    physical_sessions,
    templates,
    assistants,
    wallet,
    integrations,
    commerce,
    payments,
    accounting,
    professional_governance,
    expert_portal,
    assurance,
    privacy_ops,
    quality,
    threat_model,
    professional_profile,
    ecosystem_builder,
):
    router.include_router(module.router)
