"""Evidence-first corpus-to-learning coverage API.

This endpoint exposes aggregate implementation truth only. It does not expose
restricted corpus titles or pretend that autogenerated LX fallback is authored
pedagogical content.
"""

from __future__ import annotations

from fastapi import APIRouter

from corpus_812 import (
    EXPECTED_CORPUS_COUNT,
    EXPECTED_FORMATION_COUNT,
    SOURCE_RANGE,
    SOURCE_SHEET,
    SOURCE_WORKBOOK,
    legacy_mapping_report,
    runtime_coverage,
)
from db import db

router = APIRouter(prefix="/corpus", tags=["corpus"])


@router.get("/learning/summary")
async def learning_coverage_summary():
    """Return aggregate evidence for corpus → runtime learning reconciliation."""
    runtime_formations = await db.formations.find({}, {"_id": 0}).to_list(1000)
    coverage = runtime_coverage(runtime_formations)
    legacy = legacy_mapping_report()

    # Do not expose individual restricted/internal corpus codes here. Aggregate
    # counts are enough for health/reconciliation dashboards.
    return {
        "source": {
            "workbook": SOURCE_WORKBOOK,
            "sheet": SOURCE_SHEET,
            "range": SOURCE_RANGE,
        },
        "corpus": {
            "rows": EXPECTED_CORPUS_COUNT,
            "formations": EXPECTED_FORMATION_COUNT,
        },
        "runtime": {
            "formations": coverage["runtime_formations"],
            "direct_canonical": coverage["runtime_direct_canonical"],
            "legacy_only": coverage["runtime_legacy_only"],
            "complete_module_structure": coverage[
                "runtime_with_complete_module_structure"
            ],
            "complete_authored_learning_content": coverage[
                "runtime_with_complete_authored_content"
            ],
            "fallback_only": coverage["runtime_fallback_only"],
        },
        "legacy_baseline": {
            "expected_runtime_formations": legacy["runtime_count"],
            "direct_canonical": legacy["direct_canonical_count"],
            "requires_explicit_migration": legacy["legacy_only_count"],
        },
        "definition": {
            "module_structure_is_not_learning_content": True,
            "lx_autogenerated_fallback_counts_as_authored_content": False,
        },
    }
