"""Canonical 2D corpus formation projection and learning-coverage helpers.

Source of truth:
CVLN_Academy_Cartographie_2D_Master.xlsx / Master_Catalogue!A1:H813.

The workbook stays authoritative. This module stores only the derived formation-code
projection required to reconcile the 812-row corpus with runtime learning objects.
It deliberately distinguishes module structure from authored learning content: the
LX v2 autogenerated fallback is not counted as real pedagogical content.
"""

from __future__ import annotations

import hashlib
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, Sequence

from economy_3d import record_by_code

DATA_PATH = Path(__file__).parent / "data" / "corpus_812_formations_v1.txt"
EXPECTED_CORPUS_COUNT = 812
EXPECTED_FORMATION_COUNT = 554
EXPECTED_FORMATION_PROJECTION_SHA256 = (
    "dbd8feae83f84bc7e2b1c051d181a4df9e79e06c60fece4fba193c86295dd59c"
)
SOURCE_WORKBOOK = "CVLN_Academy_Cartographie_2D_Master.xlsx"
SOURCE_SHEET = "Master_Catalogue"
SOURCE_RANGE = "A1:H813"

LEGACY_RUNTIME_CODES: tuple[str, ...] = (
    "FMS-01",
    "FMS-02",
    "FMS-03",
    "FMS-04",
    "FMS-05",
    "FMS-06",
    "KOR-01",
    "KOR-02",
    "GMD-01",
    "SAY-01",
    "KLT-01",
    "KLT-02",
    "KLT-03",
    "KLT-04",
    "KLT-05",
    "FRK-01",
    "FRK-02",
    "FRK-03",
    "LOS-01",
    "LOS-02",
    "LOS-03",
    "BRN-01",
    "BRN-02",
    "BRN-03",
    "AGR-01",
    "BCH-01",
    "HOS-01",
    "GRP-01",
    "GRP-02",
    "CIP-01",
)

# Fields that can prove authored/persisted learning material exists. Generic LX v2
# fallback fields (hook/name/deliverable) are intentionally excluded.
_AUTHORED_TEXT_FIELDS = (
    "authored_content_md",
    "course_content_md",
    "lesson_body_md",
    "lesson_body",
    "content_md",
)
_AUTHORED_SEQUENCE_FIELDS = (
    "lessons",
    "learning_units",
)
_AUTHORED_MEDIA_FIELDS = (
    "video_url",
    "video_asset_id",
    "pdf_url",
    "course_asset_id",
)


class Corpus812Error(RuntimeError):
    """Raised when the canonical 2D projection violates its contract."""


@lru_cache(maxsize=1)
def formation_codes() -> tuple[str, ...]:
    raw = DATA_PATH.read_bytes()
    projection_hash = hashlib.sha256(raw).hexdigest()
    if projection_hash != EXPECTED_FORMATION_PROJECTION_SHA256:
        raise Corpus812Error("2D formation projection SHA-256 drift")

    codes = tuple(
        line.strip().upper()
        for line in raw.decode("utf-8").splitlines()
        if line.strip()
    )
    if len(codes) != EXPECTED_FORMATION_COUNT:
        raise Corpus812Error(
            f"expected {EXPECTED_FORMATION_COUNT} canonical formations, got {len(codes)}"
        )
    if len(set(codes)) != len(codes):
        raise Corpus812Error("duplicate canonical formation code")

    # Economy 3D is also 812-line canonical truth. Every canonical pedagogical
    # formation must have an economic classification, even when NOT_FOR_SALE.
    missing_economy = []
    for code in codes:
        try:
            record_by_code(code)
        except KeyError:
            missing_economy.append(code)
    if missing_economy:
        raise Corpus812Error(
            "canonical formations missing Economy 3D mapping: "
            + ", ".join(missing_economy[:20])
        )
    return codes


def iter_formation_codes() -> Iterable[str]:
    return iter(formation_codes())


def canonical_formation_set() -> set[str]:
    return set(formation_codes())


def legacy_mapping_report(
    runtime_codes: Sequence[str] = LEGACY_RUNTIME_CODES,
) -> Dict[str, Any]:
    canonical = canonical_formation_set()
    normalized = [str(code).strip().upper() for code in runtime_codes]
    direct = [code for code in normalized if code in canonical]
    legacy_only = [code for code in normalized if code not in canonical]
    return {
        "runtime_count": len(normalized),
        "direct_canonical_count": len(direct),
        "legacy_only_count": len(legacy_only),
        "direct_canonical_codes": direct,
        "legacy_only_codes": legacy_only,
    }


def module_has_structure(module: Dict[str, Any]) -> bool:
    """A module has pedagogical structure when it has an identity and output."""
    return bool(
        str(module.get("code") or "").strip()
        and str(module.get("name") or "").strip()
        and str(module.get("deliverable") or "").strip()
    )


def module_has_authored_content(module: Dict[str, Any]) -> bool:
    """Return True only for authored/persisted course material.

    The generic content created by ``lx.enrich_module`` is intentionally not proof:
    it is generated from module metadata and explicitly contains video placeholders.
    """
    for field in _AUTHORED_TEXT_FIELDS:
        value = module.get(field)
        if isinstance(value, str) and len(value.strip()) >= 500:
            return True

    for field in _AUTHORED_SEQUENCE_FIELDS:
        value = module.get(field)
        if isinstance(value, list) and value:
            # Require at least one substantial lesson/unit, not just a title stub.
            for item in value:
                if not isinstance(item, dict):
                    continue
                body = (
                    item.get("content_md")
                    or item.get("body")
                    or item.get("body_md")
                )
                if isinstance(body, str) and len(body.strip()) >= 300:
                    return True

    # A real course media asset counts only when paired with some authored support
    # text/resources, so an empty video URL alone cannot pass the gate.
    has_media = any(
        str(module.get(field) or "").strip() for field in _AUTHORED_MEDIA_FIELDS
    )
    resources = module.get("resources")
    has_resources = isinstance(resources, list) and len(resources) > 0
    return bool(has_media and has_resources)


def formation_learning_evidence(formation: Dict[str, Any]) -> Dict[str, Any]:
    modules = formation.get("modules") or []
    structured = [
        m for m in modules if isinstance(m, dict) and module_has_structure(m)
    ]
    authored = [
        m for m in modules if isinstance(m, dict) and module_has_authored_content(m)
    ]
    total = len(modules)
    return {
        "code": str(formation.get("code") or "").upper(),
        "module_count": total,
        "structured_module_count": len(structured),
        "authored_module_count": len(authored),
        "module_structure_complete": total > 0 and len(structured) == total,
        "authored_learning_content_complete": total > 0 and len(authored) == total,
        "uses_only_fallback_content": total > 0 and len(authored) == 0,
    }


def runtime_coverage(runtime_formations: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    canonical = canonical_formation_set()
    runtime_by_code = {
        str(f.get("code") or "").strip().upper(): f
        for f in runtime_formations
        if str(f.get("code") or "").strip()
    }

    canonical_runtime = sorted(code for code in runtime_by_code if code in canonical)
    legacy_only = sorted(code for code in runtime_by_code if code not in canonical)
    evidence = [
        formation_learning_evidence(runtime_by_code[code]) for code in runtime_by_code
    ]

    with_structure = sum(1 for item in evidence if item["module_structure_complete"])
    with_authored_content = sum(
        1 for item in evidence if item["authored_learning_content_complete"]
    )
    fallback_only = sum(1 for item in evidence if item["uses_only_fallback_content"])

    return {
        "corpus_rows": EXPECTED_CORPUS_COUNT,
        "canonical_formations": EXPECTED_FORMATION_COUNT,
        "runtime_formations": len(runtime_by_code),
        "runtime_direct_canonical": len(canonical_runtime),
        "runtime_legacy_only": len(legacy_only),
        "runtime_with_complete_module_structure": with_structure,
        "runtime_with_complete_authored_content": with_authored_content,
        "runtime_fallback_only": fallback_only,
        "direct_canonical_codes": canonical_runtime,
        "legacy_only_codes": legacy_only,
        "formations": evidence,
    }
