"""Detailed modules for the 25 formations that were shipped as "coming_soon" in v1.

Each formation gets 6-12 modules following the CVLN Master OS structure:
- code / name / duration_h / stade / hook / deliverable / frek_signal

Stades: graine | pousse | racine | branches | arbre | foret
FREK signals: FREK-WORK | FREK-SCORE | FREK-LINK | FREK-CERT | FREK-CONTRIB
"""

EXTRA_MODULES = {
    # ============ FMS (Factory Maker Studio) — 3 formations ============
    "FMS-04": [  # Branding artistique — 36h, stades pousse→arbre
        {
            "code": "FMS-04-M01",
            "name": "Fondamentaux du branding artistique",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "3 marques d'artistes caribéens décortiquées",
            "deliverable": "Note de positionnement 1 page",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-04-M02",
            "name": "Analyse d'archétypes de marque",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Zouk Machine vs Kalash — deux archétypes opposés",
            "deliverable": "Fiche archétype personnel argumentée",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FMS-04-M03",
            "name": "Identité visuelle — logo, palette, typographie",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Charte visuelle live d'un featuring caribéen",
            "deliverable": "Kit visuel (logo + 3 palettes + typo)",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-04-M04",
            "name": "Storytelling artistique et ligne éditoriale",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Interview d'artiste : ligne narrative révélée",
            "deliverable": "Storyline 12 mois écrite",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-04-M05",
            "name": "Charte de marque personnelle complète",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Charte pro examinée",
            "deliverable": "Charte de marque 8 pages",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FMS-04-M06",
            "name": "Directions artistiques par plateforme (IG, TikTok, Spotify Canvas)",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Feed IG cohérent vs incohérent A/B",
            "deliverable": "3 templates plateforme + calendrier de contenu",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-04-M07",
            "name": "Merchandising et objets identitaires",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Merch drop 24h sold out étude cas",
            "deliverable": "Ligne merch 3 pièces + BOM prix",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-04-M08",
            "name": "Rebranding — quand pivoter sans se trahir",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Pivot d'un artiste diaspora",
            "deliverable": "Note de rebranding 3 pages + timeline",
            "frek_signal": "FREK-CERT",
        },
    ],
    "FMS-05": [  # Management d'artiste — 32h, stades pousse→arbre
        {
            "code": "FMS-05-M01",
            "name": "Le rôle réel du manager en 2026",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Interview 2 managers caribéens live",
            "deliverable": "Cahier des charges du manager (2 pages)",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-05-M02",
            "name": "Contrat de management — clauses vitales",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Contrat piège lu en public",
            "deliverable": "Contrat de management personnalisé",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FMS-05-M03",
            "name": "Booking et négociation de cachets",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Cachets réels antillais dévoilés",
            "deliverable": "Grille tarifaire 5 niveaux",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-05-M04",
            "name": "Tour management — logistique et budget",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Tourbook d'une tournée Antilles",
            "deliverable": "Tourbook complet 5 dates",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-05-M05",
            "name": "Comptabilité artiste — split, avance, royalties",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Décompte royalties expliqué",
            "deliverable": "Simulateur split Excel + note de synthèse",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FMS-05-M06",
            "name": "Négocier avec labels et plateformes",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Deal DSP vs label vs indie A/B",
            "deliverable": "Mémo de négociation + arbre de décision",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "FMS-05-M07",
            "name": "Psychologie et rythme d'artiste",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Burnout artistique témoignage",
            "deliverable": "Charte relationnelle manager/artiste",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-05-M08",
            "name": "Cas pratique — piloter 3 dates réelles",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Simulation live de 3 crises",
            "deliverable": "Rapport post-tour + feedback artiste",
            "frek_signal": "FREK-CERT",
        },
    ],
    "FMS-06": [  # Production exécutive — 28h, arbre→foret
        {
            "code": "FMS-06-M01",
            "name": "EP : rôle, périmètre, responsabilités",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "EP major vs EP indépendant",
            "deliverable": "Fiche métier EP + cartographie de projet",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-06-M02",
            "name": "Sélection artistique et A&R stratégique",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Signing raté étude cas",
            "deliverable": "Grille d'évaluation d'artiste + shortlist 5",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FMS-06-M03",
            "name": "Budget prévisionnel et P&L d'album",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "P&L album EP réel lu",
            "deliverable": "P&L complet 24 mois",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FMS-06-M04",
            "name": "Coordination de studio et calendrier",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Session studio filmée",
            "deliverable": "Gantt de production 90 jours",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FMS-06-M05",
            "name": "Deals internationaux — sync, license, master",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Deal Warner-caribéen expliqué",
            "deliverable": "Term sheet complet annoté",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "FMS-06-M06",
            "name": "Green-lighting — décider en connaissance de cause",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Session green-light live",
            "deliverable": "Dossier de green-light 15 slides",
            "frek_signal": "FREK-CERT",
        },
        {
            "code": "FMS-06-M07",
            "name": "Pitch EP à un label ou fonds — masterclass finale",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Pitch réel investisseur culturel",
            "deliverable": "Pitch deck EP + vidéo 5 min",
            "frek_signal": "FREK-CONTRIB",
        },
    ],
    # ============ KOR (KORA) — 2 formations ============
    "KOR-01": [  # Podcast Production — 31h, graine→branches
        {
            "code": "KOR-01-M01",
            "name": "Anatomie d'un podcast qui accroche",
            "duration_h": 4,
            "stade": "graine",
            "hook": "1er épisode viral décortiqué",
            "deliverable": "Analyse d'un podcast caribéen référence",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KOR-01-M02",
            "name": "Choisir sujet, format, cadence",
            "duration_h": 3,
            "stade": "graine",
            "hook": "3 formats KORA testés en live",
            "deliverable": "One-pager concept + 10 idées d'épisodes",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KOR-01-M03",
            "name": "Écriture d'un script d'épisode",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Script vs improvisation A/B",
            "deliverable": "Script complet d'un épisode 20 min",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KOR-01-M04",
            "name": "Prise de son — home vs studio",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Même prise 3 setups audio",
            "deliverable": "Prise de son de 15 min montée",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KOR-01-M05",
            "name": "Montage et sound design",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Montage brut vs monté",
            "deliverable": "Épisode monté 20 min",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KOR-01-M06",
            "name": "Habillage sonore et générique KORA",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Génériques cultes analysés",
            "deliverable": "Jingle + générique 30 s original",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KOR-01-M07",
            "name": "Distribution — hébergeurs, RSS, DSP",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Setup RSS live",
            "deliverable": "Podcast publié sur 3 plateformes",
            "frek_signal": "FREK-CERT",
        },
        {
            "code": "KOR-01-M08",
            "name": "Croissance et monétisation — comm, sponsors, Patreon",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Podcast diaspora 10k abonnés",
            "deliverable": "Plan de croissance 6 mois + kit sponsors",
            "frek_signal": "FREK-CONTRIB",
        },
    ],
    "KOR-02": [  # Media Storytelling — 28h, pousse→arbre
        {
            "code": "KOR-02-M01",
            "name": "Le journalisme culturel caribéen aujourd'hui",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "5 unes culturelles décortiquées",
            "deliverable": "Note d'analyse 2 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KOR-02-M02",
            "name": "Angle, source, vérification",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Fake news culturelle démontée",
            "deliverable": "Fiche source + protocole de vérif",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KOR-02-M03",
            "name": "Écriture longue — feature, portrait, reportage",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Portrait d'artiste comparé 3 auteurs",
            "deliverable": "Feature 2500 mots publiable",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KOR-02-M04",
            "name": "Multiformats — texte, audio, vidéo, réseaux",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Un sujet 4 formats côte à côte",
            "deliverable": "Sujet décliné en 4 formats",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KOR-02-M05",
            "name": "Éthique et déontologie culturelle",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Cas éthiques réels ouverts",
            "deliverable": "Charte perso + arbre de décision éthique",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KOR-02-M06",
            "name": "Distribution KORA et co-productions",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Co-prod KORA live analysée",
            "deliverable": "Pitch de co-production KORA",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "KOR-02-M07",
            "name": "Portfolio et signature — devenir référence",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Journaliste culturel star étudié",
            "deliverable": "Portfolio publiable + bio publique",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ GMD (Good Mood) — 1 formation ============
    "GMD-01": [  # Festival & événementiel — 52h, graine→arbre
        {
            "code": "GMD-01-M01",
            "name": "Écosystème festival caribéen",
            "duration_h": 4,
            "stade": "graine",
            "hook": "3 festivals caribéens en chiffres",
            "deliverable": "Cartographie 10 festivals + fiche synthèse",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "GMD-01-M02",
            "name": "Concept & scénographie d'événement",
            "duration_h": 5,
            "stade": "graine",
            "hook": "Concept festival live pitché",
            "deliverable": "Concept doc 5 pages + moodboard",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "GMD-01-M03",
            "name": "Programmation artistique équilibrée",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Lineups vus/pas vus",
            "deliverable": "Programmation 20 artistes annotée",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "GMD-01-M04",
            "name": "Budget d'événement — 250k€ CVLN CC2026",
            "duration_h": 6,
            "stade": "pousse",
            "hook": "Budget festival réel disséqué",
            "deliverable": "Budget prévisionnel complet + P&L",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "GMD-01-M05",
            "name": "Sécurité, réglementaire, assurances",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Incident festival étude cas",
            "deliverable": "Dossier sécurité complet + PPI",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "GMD-01-M06",
            "name": "Régie technique — son, lumière, plateau",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Fiches techniques 3 formats",
            "deliverable": "Rider technique festival + planning régie",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "GMD-01-M07",
            "name": "Comm et billetterie",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Campagne festival caribéen étudiée",
            "deliverable": "Plan de comm 90 jours + landing billetterie",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "GMD-01-M08",
            "name": "Bénévoles et coordination J-day",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Runbook J-day analysé",
            "deliverable": "Runbook J-1/J/J+1 opérationnel",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "GMD-01-M09",
            "name": "Écoresponsabilité et impact local",
            "duration_h": 6,
            "stade": "arbre",
            "hook": "Festival zéro-déchet documenté",
            "deliverable": "Charte RSE + KPI mesurables",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "GMD-01-M10",
            "name": "Post-mortem et re-conduction",
            "duration_h": 6,
            "stade": "arbre",
            "hook": "Debrief CC2025 archivé",
            "deliverable": "Post-mortem structuré + roadmap N+1",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ SAY (DJ SAYD) — 1 formation ============
    "SAY-01": [  # Personal Brand & Cultural Leadership — 48h, pousse→foret
        {
            "code": "SAY-01-M01",
            "name": "Définir sa boussole culturelle personnelle",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Manifeste DJ SAYD lu",
            "deliverable": "Boussole personnelle 1 page",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "SAY-01-M02",
            "name": "Récit d'origine — d'où tu viens vraiment",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Récit d'origine live d'un leader",
            "deliverable": "Texte 800 mots + vidéo 3 min",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "SAY-01-M03",
            "name": "Prise de parole publique — voix authentique",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Bad speech vs good speech A/B",
            "deliverable": "Vidéo prise de parole 5 min",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "SAY-01-M04",
            "name": "Écriture d'un manifeste personnel",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Manifestes iconiques comparés",
            "deliverable": "Manifeste 1 page publié",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "SAY-01-M05",
            "name": "Réseaux — construire sa présence sans se dénaturer",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Présence sociale d'un leader décortiquée",
            "deliverable": "Éditorial 90 jours cohérent",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "SAY-01-M06",
            "name": "Diplomatie culturelle et alliances",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Alliance culturelle diaspora réussie",
            "deliverable": "Cartographie 20 alliés cibles + note",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "SAY-01-M07",
            "name": "Leadership d'entité — diriger sans écraser",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Style de leadership DJ SAYD analysé",
            "deliverable": "Charte de leadership personnelle",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "SAY-01-M08",
            "name": "Prendre la parole en institution — OIF, DAC, CTM",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Intervention institutionnelle réelle",
            "deliverable": "Intervention préparée + note stratégique",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "SAY-01-M09",
            "name": "Legs et transmission — au-delà de soi",
            "duration_h": 5,
            "stade": "foret",
            "hook": "Transmission culturelle générationnelle",
            "deliverable": "Plan de transmission 5 ans",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "SAY-01-M10",
            "name": "Prise de parole finale — CC2026 keynote",
            "duration_h": 5,
            "stade": "foret",
            "hook": "Keynote CC2025 revisitée",
            "deliverable": "Keynote 15 min publique captée",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ KLT (Kiltikonet) — 5 formations ============
    "KLT-01": [  # Médiation culturelle caribéenne — 42h, graine→racine
        {
            "code": "KLT-01-M01",
            "name": "Qu'est-ce que médier une culture ?",
            "duration_h": 4,
            "stade": "graine",
            "hook": "Médiation ratée vs réussie A/B",
            "deliverable": "Note personnelle 500 mots + carte des rôles",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-01-M02",
            "name": "Panorama culturel caribéen — ancêtres, langues, gestes",
            "duration_h": 5,
            "stade": "graine",
            "hook": "10 objets culturels décodés",
            "deliverable": "Fiches 5 objets culturels",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-01-M03",
            "name": "Concevoir un atelier de médiation",
            "duration_h": 5,
            "stade": "graine",
            "hook": "Atelier caribéen live",
            "deliverable": "Fiche atelier 1h détaillée",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-01-M04",
            "name": "Animer un groupe — dynamique et sécurité affective",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Groupe difficile — simulation vidéo",
            "deliverable": "Grille d'animation + posture personnelle",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-01-M05",
            "name": "Média et outils de médiation (podcast, IG, livrets)",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Livret culturel réussi lu",
            "deliverable": "Livret pédagogique 8 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-01-M06",
            "name": "Interculturel — respecter sans folkloriser",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Folklorisation vue et disséquée",
            "deliverable": "Grille d'auto-check interculturelle",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-01-M07",
            "name": "Publics jeunes (12-25) — codes et outils",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Atelier jeunes filmé",
            "deliverable": "Atelier jeune public conduit + retour",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-01-M08",
            "name": "Publics seniors et transmission orale",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Aïeul.e caribéen interviewé",
            "deliverable": "Interview mémorielle 30 min transcrite",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "KLT-01-M09",
            "name": "Certification ambassadeur Kiltikonet",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Test ambassadeur simulé",
            "deliverable": "Dossier certification + soutenance",
            "frek_signal": "FREK-CERT",
        },
    ],
    "KLT-02": [  # Montage & gestion projets culturels — 56h, pousse→arbre
        {
            "code": "KLT-02-M01",
            "name": "L'idée devenue projet — from brief to brief",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Idée abandonnée vs déployée",
            "deliverable": "Brief projet culturel 2 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-02-M02",
            "name": "Étude de besoin et parties prenantes",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Étude terrain KLT réelle",
            "deliverable": "Étude de besoin 5 pages + carte acteurs",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-02-M03",
            "name": "Budget culturel prévisionnel",
            "duration_h": 6,
            "stade": "racine",
            "hook": "Budget dépollué en direct",
            "deliverable": "Budget complet + trésorerie 18 mois",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-02-M04",
            "name": "Recherche de financements — DAC, CTM, OIF, mécénat",
            "duration_h": 6,
            "stade": "racine",
            "hook": "Grants obtenus / refusés listés",
            "deliverable": "Dossier de financement complet + 3 pistes",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-02-M05",
            "name": "Planification et gestion des équipes",
            "duration_h": 6,
            "stade": "racine",
            "hook": "Gantt culturel montré",
            "deliverable": "Gantt + org chart projet",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-02-M06",
            "name": "Suivi opérationnel et pilotage",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Comité de pilotage vécu",
            "deliverable": "Tableau de bord + rythme de comité",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-02-M07",
            "name": "Communication de projet — récit et preuves",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Récit de projet inspirant",
            "deliverable": "Kit de comm 5 formats + plan média",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "KLT-02-M08",
            "name": "Évaluation d'impact culturel",
            "duration_h": 6,
            "stade": "arbre",
            "hook": "Rapport d'impact CTM décortiqué",
            "deliverable": "Grille d'évaluation + rapport 6 pages",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-02-M09",
            "name": "Bilan et reconduction stratégique",
            "duration_h": 6,
            "stade": "arbre",
            "hook": "Projet reconduit 3 fois",
            "deliverable": "Bilan + roadmap 3 ans",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "KLT-02-M10",
            "name": "Soutenance publique — jury Kiltikonet",
            "duration_h": 6,
            "stade": "arbre",
            "hook": "Soutenances passées filmées",
            "deliverable": "Soutenance publique 20 min + Q&A",
            "frek_signal": "FREK-CERT",
        },
    ],
    "KLT-03": [  # Stratégie institutionnelle — 44h, racine→foret
        {
            "code": "KLT-03-M01",
            "name": "Cartographie des institutions culturelles",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Org chart OIF/UNESCO/DAC en direct",
            "deliverable": "Cartographie 30 institutions annotée",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-03-M02",
            "name": "OIF — Organisation internationale de la Francophonie",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Grant OIF obtenu étude cas",
            "deliverable": "Dossier OIF-ready + fiche calendrier",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-03-M03",
            "name": "UNESCO et CARIFESTA — patrimoine et rayonnement",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Inscription UNESCO en pratique",
            "deliverable": "Note de positionnement UNESCO",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-03-M04",
            "name": "DAC, CTM et écosystème local",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Rapport CTM ouvert",
            "deliverable": "Dossier DAC/CTM complet",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-03-M05",
            "name": "Fonds européens — Creative Europe, ERDF",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Projet EU financé décortiqué",
            "deliverable": "Consortium letter + budget EU",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "KLT-03-M06",
            "name": "Diplomatie culturelle et soft power",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Diplomatie du zouk expliquée",
            "deliverable": "Note de diplomatie culturelle personnelle",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-03-M07",
            "name": "Représentation en instances (conseils, comités)",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Prise de parole en instance filmée",
            "deliverable": "Intervention préparée 10 min",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "KLT-03-M08",
            "name": "Lobbying culturel — éthique et efficacité",
            "duration_h": 5,
            "stade": "foret",
            "hook": "Lobby culturel réussi",
            "deliverable": "Plan de lobbying 12 mois",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "KLT-03-M09",
            "name": "Mission institutionnelle finale — représenter Kiltikonet",
            "duration_h": 5,
            "stade": "foret",
            "hook": "Représentation Kiltikonet OIF",
            "deliverable": "Mission institutionnelle documentée + note post-mortem",
            "frek_signal": "FREK-CERT",
        },
    ],
    "KLT-04": [  # Gouvernance associative — 38h, racine→arbre
        {
            "code": "KLT-04-M01",
            "name": "La loi 1901 en pratique",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Statuts d'une asso caribéenne lus",
            "deliverable": "Statuts modèles annotés",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-04-M02",
            "name": "Créer une association culturelle",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Déclaration en préfecture live",
            "deliverable": "Dossier de création complet déposé",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-04-M03",
            "name": "Rôles — Président, Trésorier, Secrétaire, DAF",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Cas de conflit CA analysé",
            "deliverable": "Fiches de rôles + charte de gouvernance",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-04-M04",
            "name": "Comptabilité associative et plan comptable",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Bilan associatif décortiqué",
            "deliverable": "Bilan + compte de résultat modèle",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-04-M05",
            "name": "Fiscalité culturelle — 1901 vs 1901 lucrative",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Contrôle fiscal culturel réel",
            "deliverable": "Note fiscale 3 pages + arbre de décision",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-04-M06",
            "name": "AG, PV et documents obligatoires",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "AG conflictuelle vue",
            "deliverable": "PV type AGO + AGE modèle",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-04-M07",
            "name": "Gestion salariale et bénévolat",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Contrat CDDU intermittent expliqué",
            "deliverable": "Fiche paie modèle + convention de bénévolat",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-04-M08",
            "name": "Cas pratique — auditer une association",
            "duration_h": 6,
            "stade": "arbre",
            "hook": "Audit associatif live",
            "deliverable": "Rapport d'audit 10 pages",
            "frek_signal": "FREK-CERT",
        },
    ],
    "KLT-05": [  # Kiltikonet plateforme — 40h, pousse→foret
        {
            "code": "KLT-05-M01",
            "name": "Kiltikonet — mission, valeurs, architecture",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Tour d'écran Kiltikonet.fr",
            "deliverable": "Note d'onboarding Kiltikonet 2 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-05-M02",
            "name": "Community management diaspora",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Community caribéenne étudiée",
            "deliverable": "Editorial 30 jours + KPIs engagement",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-05-M03",
            "name": "Modération culturelle — sécurité et pluralité",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Débat difficile modéré",
            "deliverable": "Charte de modération + arbre décision",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-05-M04",
            "name": "Contenus Kiltikonet — capsules, dossiers, empreintes",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Capsule Kiltikonet virale",
            "deliverable": "3 formats de contenu prêts",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "KLT-05-M05",
            "name": "Analytics et lecture de l'engagement",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Dashboard interne présenté",
            "deliverable": "Rapport analytics 1 mois + reco",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "KLT-05-M06",
            "name": "Partenariats plateforme — labels, festivals, institutions",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Deal plateforme réel décortiqué",
            "deliverable": "Term sheet partenariat plateforme",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "KLT-05-M07",
            "name": "Événements Kiltikonet IRL",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Meetup diaspora réussi",
            "deliverable": "Meetup Kiltikonet organisé + rapport",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "KLT-05-M08",
            "name": "Devenir opérateur senior Kiltikonet",
            "duration_h": 6,
            "stade": "foret",
            "hook": "Passage de témoin senior décrit",
            "deliverable": "Dossier opérateur + soutenance",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ FRK (FREK) — 2 formations restantes ============
    "FRK-02": [  # Digital Provenance Specialist — 28h, branches→foret
        {
            "code": "FRK-02-M01",
            "name": "Provenance numérique — pourquoi ça change tout",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Preuve culturelle contestée réelle",
            "deliverable": "Note de cadrage provenance 2 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FRK-02-M02",
            "name": "Écosystème FREK — deep dive technique",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Architecture FREK dévoilée",
            "deliverable": "Schéma technique FREK annoté",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FRK-02-M03",
            "name": "FREK vs alternatives (Numbers Protocol, C2PA)",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Comparatif live 3 protocoles",
            "deliverable": "Étude comparative 4 pages",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FRK-02-M04",
            "name": "Notariat numérique — audit et contre-expertise",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Contentieux FREK-vérifié résolu",
            "deliverable": "Rapport d'expertise 1 œuvre",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FRK-02-M05",
            "name": "Cas juridiques — droits d'auteur augmenté par FREK",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Jurisprudence culturelle 2025",
            "deliverable": "Mémo juridique 5 pages",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FRK-02-M06",
            "name": "Consultation externe — accompagner un artiste",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Session conseil FREK réelle",
            "deliverable": "Mission d'accompagnement + livrable client",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "FRK-02-M07",
            "name": "Certification FREK Senior Specialist",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Examen certif observé",
            "deliverable": "Certification passée avec dossier",
            "frek_signal": "FREK-CERT",
        },
    ],
    "FRK-03": [  # Archivage culturel sécurisé — 22h, pousse→arbre
        {
            "code": "FRK-03-M01",
            "name": "Pourquoi archiver l'oralité caribéenne maintenant",
            "duration_h": 3,
            "stade": "pousse",
            "hook": "Voix perdue de gwo-ka réentendue",
            "deliverable": "Note d'urgence archivistique 1 page",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FRK-03-M02",
            "name": "Standards UNESCO et archivistique numérique",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Norme OAIS expliquée",
            "deliverable": "Fiche standards + protocole",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FRK-03-M03",
            "name": "Collecte terrain — éthique, RGPD, consentement",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Collecte terrain filmée",
            "deliverable": "Kit consentement + protocole terrain",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FRK-03-M04",
            "name": "Traitement, indexation et tagging FREK",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Indexation manuelle vs IA",
            "deliverable": "20 œuvres taggées et empreintes FREK",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "FRK-03-M05",
            "name": "Stockage sécurisé et longévité 30 ans",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Perte de donnée archivée témoignée",
            "deliverable": "Plan de stockage triplé + audit",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "FRK-03-M06",
            "name": "Livraison à CIP Foundation",
            "duration_h": 3,
            "stade": "arbre",
            "hook": "Dépôt CIP standardisé",
            "deliverable": "Dépôt CIP conforme + accusé de réception",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ LOS (LabelOS) — 3 formations ============
    "LOS-01": [  # Label Operations Manager — 42h, pousse→arbre
        {
            "code": "LOS-01-M01",
            "name": "Anatomie d'un label indépendant 2026",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Labels indés caribéens listés",
            "deliverable": "Cartographie 15 labels + fiche",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-01-M02",
            "name": "LabelOS — tour complet des modules",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Écrans LabelOS montrés",
            "deliverable": "Note d'onboarding LabelOS 3 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-01-M03",
            "name": "Signing — recruter artistes et catalogues",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Signing raté vs réussi",
            "deliverable": "Fiche signing standard label",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "LOS-01-M04",
            "name": "Cycle album — plan de sortie et coordination",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Album cycle 6 mois vue globale",
            "deliverable": "Gantt cycle album 12 mois complet",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-01-M05",
            "name": "Contrats label — édition, master, sync",
            "duration_h": 5,
            "stade": "branches",
            "hook": "3 types de contrat A/B/C",
            "deliverable": "3 contrats types annotés",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "LOS-01-M06",
            "name": "Royalties, splits et reporting artistes",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Décompte royalties opaque vs transparent",
            "deliverable": "Rapport royalties trimestriel modèle",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-01-M07",
            "name": "Sync, licensing et deals internationaux",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Sync majeur caribéen décortiqué",
            "deliverable": "Pitch sync + tracker 20 opportunités",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "LOS-01-M08",
            "name": "IA + label — LabelOS × CVLN Brain",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Workflow IA appliqué au label",
            "deliverable": "Workflow IA documenté + gains chiffrés",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-01-M09",
            "name": "Certification Label Ops Manager",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Certif LabelOS simulée",
            "deliverable": "Dossier certif + soutenance",
            "frek_signal": "FREK-CERT",
        },
    ],
    "LOS-02": [  # Metadata & Catalog Management — 26h, pousse→arbre
        {
            "code": "LOS-02-M01",
            "name": "Pourquoi les metadata valent des royalties",
            "duration_h": 3,
            "stade": "pousse",
            "hook": "Royalties perdues caribéennes chiffrées",
            "deliverable": "Note d'impact metadata 1 page",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-02-M02",
            "name": "Standards — ISRC, ISWC, UPC, IPI, DDEX",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Codes musicaux décodés",
            "deliverable": "Cheatsheet standards + 3 cas",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "LOS-02-M03",
            "name": "Nettoyage de catalogue — audit et correction",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Catalogue sale audité",
            "deliverable": "50 tracks nettoyées documentées",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-02-M04",
            "name": "Contribution complète — writers, producers, features",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Contribution oubliée retrouvée",
            "deliverable": "Fiche contribution complète 10 tracks",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-02-M05",
            "name": "Distribution DDEX — feed propre vers DSP",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Feed DDEX cassé vs bon",
            "deliverable": "DDEX feed testé et validé",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-02-M06",
            "name": "Collecte SACEM/SCPP/PPL — récupérer les royalties",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Réclamation SACEM aboutie",
            "deliverable": "Dossier de réclamation complet",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "LOS-02-M07",
            "name": "Certification metadata — audit label complet",
            "duration_h": 3,
            "stade": "arbre",
            "hook": "Audit label live",
            "deliverable": "Audit metadata d'un label + rapport",
            "frek_signal": "FREK-CERT",
        },
    ],
    "LOS-03": [  # AI-Assisted Label Workflow — 26h, pousse→arbre
        {
            "code": "LOS-03-M01",
            "name": "IA au service d'un label — panorama 2026",
            "duration_h": 3,
            "stade": "pousse",
            "hook": "Label 100% IA-augmenté étudié",
            "deliverable": "Veille IA label 15 outils commentés",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-03-M02",
            "name": "IA pour A&R — scouting et scoring",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Scoring IA A/B avec humain",
            "deliverable": "Score IA + note critique 5 artistes",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "LOS-03-M03",
            "name": "IA + LabelOS — automatiser reporting",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Reporting automatisé live",
            "deliverable": "Reporting mensuel automatisé",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-03-M04",
            "name": "IA + comm — campagnes semi-automatisées",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Campagne IA vs manuelle A/B",
            "deliverable": "Campagne IA-augmentée livrée",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-03-M05",
            "name": "IA + edito catalogue — bios, notes, descriptifs",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Bio IA vs bio manager",
            "deliverable": "30 bios IA-générées + human-in-the-loop",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "LOS-03-M06",
            "name": "IA + veille marché — écouter la Caraïbe en continu",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Veille tendance live",
            "deliverable": "Dashboard veille marché + alerte",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "LOS-03-M07",
            "name": "Ethique IA label — cadre CVLN",
            "duration_h": 3,
            "stade": "arbre",
            "hook": "IA qui déraille étude cas",
            "deliverable": "Charte IA label + garde-fous",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ BRN (CVLN Brain) — 2 formations restantes ============
    "BRN-01": [  # Strategic Ecosystem Design — 32h, branches→foret
        {
            "code": "BRN-01-M01",
            "name": "Écosystème vs entreprise vs marché",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Écosystème mature caribéen étudié",
            "deliverable": "Note de cadrage écosystème 2 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "BRN-01-M02",
            "name": "Cartographie d'un écosystème (acteurs, flux, tensions)",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Carto CVLN live commentée",
            "deliverable": "Cartographie complète d'un écosystème choisi",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "BRN-01-M03",
            "name": "Modèles économiques d'écosystème",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "3 modèles éco décortiqués",
            "deliverable": "Modèle éco d'un écosystème CVLN nouvel",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "BRN-01-M04",
            "name": "Gouvernance et pactes d'associés",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Pacte gagnant vs toxique",
            "deliverable": "Pacte d'associés modèle 6 pages",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "BRN-01-M05",
            "name": "Stratégie de scale — 36 mois vers l'IPO 2028",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Plan de scale CVLN annoté",
            "deliverable": "Roadmap 36 mois d'une entité CVLN",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "BRN-01-M06",
            "name": "Partenariats stratégiques et alliances",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Alliance culturelle historique",
            "deliverable": "5 term sheets d'alliance",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "BRN-01-M07",
            "name": "Risques d'écosystème et scénarios",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Effondrement d'un écosystème décrit",
            "deliverable": "Matrice risques 20 items + plan de mitigation",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "BRN-01-M08",
            "name": "Pitch board CVLN — proposer une entité",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Pitch board live",
            "deliverable": "Pitch deck 15 slides + Q&A",
            "frek_signal": "FREK-CERT",
        },
    ],
    "BRN-03": [  # Cultural Intelligence Systems — 24h, branches→foret
        {
            "code": "BRN-03-M01",
            "name": "Qu'est-ce qu'un observatoire culturel souverain ?",
            "duration_h": 3,
            "stade": "branches",
            "hook": "Observatoire OIF pilote décrit",
            "deliverable": "Note de cadrage 2 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "BRN-03-M02",
            "name": "Sources — signaux DSP, réseaux, ventes, terrain",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Carto sources caribéennes",
            "deliverable": "Grille sources + protocole ingestion",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "BRN-03-M03",
            "name": "Data pipeline culturel — architecture technique",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Pipeline CVLN dévoilé",
            "deliverable": "Schéma pipeline + POC ingest",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "BRN-03-M04",
            "name": "Analyse et dashboards — lire un écosystème",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Dashboard exec caribéen étudié",
            "deliverable": "Dashboard 8 KPI + insights",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "BRN-03-M05",
            "name": "Publication — rapports semestriels culture caribéenne",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Rapport annuel institutionnel lu",
            "deliverable": "Rapport 20 pages semestre",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "BRN-03-M06",
            "name": "Livrer un observatoire à une institution",
            "duration_h": 5,
            "stade": "foret",
            "hook": "Livraison CTM observée",
            "deliverable": "Observatoire livré + note de mission",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ AGR (CVL Agro) — 1 formation ============
    "AGR-01": [  # Transformation agroalimentaire — 40h, pousse→arbre
        {
            "code": "AGR-01-M01",
            "name": "Panorama filière agroalimentaire caribéenne",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "Filière rhum vs cacao comparée",
            "deliverable": "Note filière + 3 opportunités",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "AGR-01-M02",
            "name": "Produit signature — de la matière au concept",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Produit local devenu icône",
            "deliverable": "Concept produit + fiche technique",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "AGR-01-M03",
            "name": "Transformation en labo — process & qualité",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Labo alimentaire visité",
            "deliverable": "Process 10 étapes documenté",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "AGR-01-M04",
            "name": "Sourcing responsable et traçabilité",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Producteur agricole local rencontré",
            "deliverable": "Contrat sourcing + carte de traçabilité",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "AGR-01-M05",
            "name": "Branding et packaging caribéen premium",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Packaging caribéen primé",
            "deliverable": "Charte packaging + BAT visuel",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "AGR-01-M06",
            "name": "Distribution — retail, e-com, HORECA",
            "duration_h": 5,
            "stade": "branches",
            "hook": "3 canaux comparés en marge",
            "deliverable": "Plan de distribution multi-canal",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "AGR-01-M07",
            "name": "Export — Europe, US, Afrique",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Rhum antillais à New York étude cas",
            "deliverable": "Plan export 12 mois 2 marchés",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "AGR-01-M08",
            "name": "Certification premium et launch produit",
            "duration_h": 6,
            "stade": "arbre",
            "hook": "Launch produit observé",
            "deliverable": "Launch réel documenté + retours",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ BCH (CVLN Blockchain) — 1 formation ============
    "BCH-01": [  # Blockchain culturelle — 36h, pousse→arbre
        {
            "code": "BCH-01-M01",
            "name": "Blockchain culturelle — au-delà des NFT",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "NFT musical qui a survécu vs hype",
            "deliverable": "Note de cadrage 2 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "BCH-01-M02",
            "name": "Tokeniser un actif culturel — cas concrets",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Tokenisation d'un master musical",
            "deliverable": "Design de tokenisation 3 cas caribéens",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "BCH-01-M03",
            "name": "Smart contracts pour royalties automatiques",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Smart contract musical exécuté live",
            "deliverable": "Smart contract déployé testnet",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "BCH-01-M04",
            "name": "Interop FREK ↔ blockchain",
            "duration_h": 5,
            "stade": "racine",
            "hook": "FREK ancré on-chain démo",
            "deliverable": "Bridge FREK-chain documenté",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "BCH-01-M05",
            "name": "Wallet et onboarding non-crypto",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Onboarding grand-mère analysé",
            "deliverable": "Parcours onboarding <60s testé",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "BCH-01-M06",
            "name": "Governance token et DAO culturelles",
            "duration_h": 4,
            "stade": "branches",
            "hook": "DAO artistique vécue",
            "deliverable": "Design de DAO culturelle 5 pages",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "BCH-01-M07",
            "name": "Éthique, réglementation MiCA et sécurité",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Rug pull culturel raconté",
            "deliverable": "Note conformité MiCA + arbre de décision",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "BCH-01-M08",
            "name": "Cas final — tokeniser un catalogue caribéen",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Catalogue tokenisé live",
            "deliverable": "Prototype de tokenisation + white paper",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ HOS (CVLN Hospitality) — 1 formation ============
    "HOS-01": [  # Hospitality & espaces créatifs — 44h, pousse→arbre
        {
            "code": "HOS-01-M01",
            "name": "Tiers-lieux culturels — panorama mondial et caribéen",
            "duration_h": 4,
            "stade": "pousse",
            "hook": "3 tiers-lieux visités",
            "deliverable": "Étude 5 tiers-lieux caribéens",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "HOS-01-M02",
            "name": "Concept de lieu hybride studio/résidence/hospi",
            "duration_h": 5,
            "stade": "pousse",
            "hook": "Lieu hybride réussi étudié",
            "deliverable": "Concept lieu 10 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "HOS-01-M03",
            "name": "Design d'expérience immersive caribéenne",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Expérience immersive locale décryptée",
            "deliverable": "Journey map + scénographie",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "HOS-01-M04",
            "name": "Programmation artistique et résidences",
            "duration_h": 5,
            "stade": "racine",
            "hook": "Résidence caribéenne vécue",
            "deliverable": "Programmation résidences 12 mois",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "HOS-01-M05",
            "name": "Modèle éco d'un lieu hybride",
            "duration_h": 5,
            "stade": "branches",
            "hook": "P&L d'un lieu culturel ouvert",
            "deliverable": "P&L + trésorerie 24 mois",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "HOS-01-M06",
            "name": "Opérations quotidiennes et équipe",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Journée type d'un manager de lieu",
            "deliverable": "Manuel opératoire du lieu + org chart",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "HOS-01-M07",
            "name": "Communication et communauté du lieu",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Communauté d'un lieu iconique",
            "deliverable": "Éditorial 90 jours + rituels de communauté",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "HOS-01-M08",
            "name": "Partenariats institutions et mécènes",
            "duration_h": 5,
            "stade": "arbre",
            "hook": "Deal mécène culturel exposé",
            "deliverable": "3 dossiers mécénat prêts",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "HOS-01-M09",
            "name": "Pilotage stratégique et évolution du lieu",
            "duration_h": 6,
            "stade": "arbre",
            "hook": "Pivot d'un lieu vécu",
            "deliverable": "Plan stratégique 3 ans + soutenance",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ GRP (CVL Group) — 2 formations ============
    "GRP-01": [  # Ecosystem Entrepreneurship — 28h, arbre→foret
        {
            "code": "GRP-01-M01",
            "name": "Entrepreneur d'écosystème vs entrepreneur classique",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "3 fondateurs interviewés",
            "deliverable": "Fiche posture personnelle",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "GRP-01-M02",
            "name": "Détecter une opportunité d'entité CVLN",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Entité CVLN née décortiquée",
            "deliverable": "3 opportunités d'entité présentées",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "GRP-01-M03",
            "name": "Cofonder — pacte, rôles, capital",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Cofondation ratée expliquée",
            "deliverable": "Term sheet cofondation + rôles",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "GRP-01-M04",
            "name": "Levée de fonds culturelle (grants + equity)",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Levée culturelle en direct",
            "deliverable": "Deck de levée + roadmap grants",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "GRP-01-M05",
            "name": "IPO 2028 — préparer une candidature CVLN",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Roadmap IPO commentée",
            "deliverable": "Note de candidature IPO + KPI",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "GRP-01-M06",
            "name": "Passer d'entrepreneur à leader de holding",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Passage à l'échelle vécu",
            "deliverable": "Plan de transition perso 12 mois",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "GRP-01-M07",
            "name": "Pitch board CVLN — devenir directeur d'entité",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Pitch d'entité observé",
            "deliverable": "Pitch d'entité 20 slides + Q&A",
            "frek_signal": "FREK-CERT",
        },
    ],
    "GRP-02": [  # Cultural Economy — 26h, branches→foret
        {
            "code": "GRP-02-M01",
            "name": "Political economy de la culture caribéenne",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Éco culturelle CTM chiffrée",
            "deliverable": "Note d'économie politique 3 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "GRP-02-M02",
            "name": "Mécanismes de financement mondiaux (Creative Europe, ACPCPE)",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Grant mondial caribéen étudié",
            "deliverable": "Carte des financements + calendrier",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "GRP-02-M03",
            "name": "Négocier avec institutions et bailleurs",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Négociation institutionnelle vécue",
            "deliverable": "Playbook de négociation + 3 scénarios",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "GRP-02-M04",
            "name": "Partenariats stratégiques et co-marques",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Co-brand culturel iconique",
            "deliverable": "3 pitchs de co-marque",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "GRP-02-M05",
            "name": "Scaling — Martinique → Caraïbe → monde",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Scale d'une marque culturelle observée",
            "deliverable": "Plan de scale 36 mois par étapes",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "GRP-02-M06",
            "name": "Impact et évaluation économique",
            "duration_h": 3,
            "stade": "foret",
            "hook": "Rapport d'impact publié analysé",
            "deliverable": "Rapport d'impact d'un projet 12 mois",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "GRP-02-M07",
            "name": "Représentation stratégique — devenir un pair",
            "duration_h": 3,
            "stade": "foret",
            "hook": "Pair reconnu témoigne",
            "deliverable": "Charte de représentation + engagement",
            "frek_signal": "FREK-CERT",
        },
    ],
    # ============ CIP (CIP Foundation) — 1 formation ============
    "CIP-01": [  # Standardisation & gouvernance — 30h, racine→foret
        {
            "code": "CIP-01-M01",
            "name": "Pourquoi un référentiel ISO culturel caribéen",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Absence de norme = préjudice réel",
            "deliverable": "Note de cadrage 3 pages",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "CIP-01-M02",
            "name": "Standards existants — UNESCO, ISO, W3C",
            "duration_h": 4,
            "stade": "racine",
            "hook": "Standards comparés en direct",
            "deliverable": "Étude comparative + gap analysis",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "CIP-01-M03",
            "name": "Rédiger un standard — méthode CIP",
            "duration_h": 5,
            "stade": "branches",
            "hook": "Standard v0 lu à haute voix",
            "deliverable": "Standard v0 d'un domaine culturel",
            "frek_signal": "FREK-WORK",
        },
        {
            "code": "CIP-01-M04",
            "name": "Comité de standardisation — animer et arbitrer",
            "duration_h": 4,
            "stade": "branches",
            "hook": "Séance de comité observée",
            "deliverable": "Compte-rendu + arbitrage 3 sujets",
            "frek_signal": "FREK-LINK",
        },
        {
            "code": "CIP-01-M05",
            "name": "Certification et audit — outillage CIP",
            "duration_h": 4,
            "stade": "arbre",
            "hook": "Audit CIP live",
            "deliverable": "Kit d'audit + rapport modèle",
            "frek_signal": "FREK-SCORE",
        },
        {
            "code": "CIP-01-M06",
            "name": "Publier et promouvoir un standard",
            "duration_h": 4,
            "stade": "foret",
            "hook": "Publication standard réussie",
            "deliverable": "Standard publié + plan d'adoption",
            "frek_signal": "FREK-CONTRIB",
        },
        {
            "code": "CIP-01-M07",
            "name": "Devenir référent CIP — soutenance finale",
            "duration_h": 5,
            "stade": "foret",
            "hook": "Référent CIP témoigne",
            "deliverable": "Dossier référent + soutenance publique",
            "frek_signal": "FREK-CERT",
        },
    ],
}
