"""ACA-0025 — the real Founder-decided DECIDED_V1 commercial catalogue.

Source: `CVLN_Academy_Master_Economie_3D_DECIDE_V1.xlsx`, sheets
`Decisions_Fondateur` (ECO-001..024), `Offres_Economiques` (the same
24 decisions' pricing/margin detail — 20 distinct sellable offers) and
`Policies` (18 commercial/operational rules) — Founder decisions dated
2026-09-06. Transcribed verbatim, not redesigned: every price, cost,
margin and policy rule below matches the source workbook exactly.

Nothing in this module is a payment/subscription/transaction record —
see models.py's module docstring for why (`NO_FAKE_PAID_STATE`).
"""

from __future__ import annotations

from typing import List

from .models import CommercialOffer, EconomicPolicy

OFFERS: List[CommercialOffer] = [
    CommercialOffer(
        offer_id="free-orientation",
        label="Free Orientation",
        engine="Acquisition",
        buyer="Individu",
        object_sold="Découverte",
        pricing_unit="Gratuit",
        price_eur=0,
        variable_cost_eur=0,
        gross_margin_eur=0,
        margin_floor_pct=0,
        source_decision_id="ECO-003",
        notes="Préviews/orientation seulement ; aucune certification ni contenu restreint.",
    ),
    CommercialOffer(
        offer_id="academy-access",
        label="Academy Access",
        engine="B2C Learning",
        buyer="Individu",
        object_sold="Bibliothèque + fondamentaux",
        pricing_unit="Mensuel",
        price_eur=24.90,
        price_eur_annual=249.0,
        variable_cost_eur=4.5,
        gross_margin_eur=20.4,
        margin_floor_pct=0.8,
        source_decision_id="ECO-004",
        notes="Fondamentaux + bibliothèque + progression.",
    ),
    CommercialOffer(
        offer_id="academy-pro",
        label="Academy Pro",
        engine="B2C Learning",
        buyer="Individu/pro",
        object_sold="Catalogue externe complet",
        pricing_unit="Mensuel",
        price_eur=69.0,
        price_eur_annual=690.0,
        variable_cost_eur=13.5,
        gross_margin_eur=55.5,
        margin_floor_pct=0.8,
        source_decision_id="ECO-005",
        notes="Catalogue externe complet + projets + simulations standards.",
    ),
    CommercialOffer(
        offer_id="academy-career",
        label="Academy Career",
        engine="B2C Career",
        buyer="Professionnel",
        object_sold="Pro + assessments + portfolio",
        pricing_unit="Mensuel",
        price_eur=129.0,
        price_eur_annual=1290.0,
        variable_cost_eur=32.0,
        gross_margin_eur=97.0,
        margin_floor_pct=0.75,
        source_decision_id="ECO-006",
        notes="Pro + portfolio + 2 assessments/an + priorité opportunités ; aucune mission garantie.",
    ),
    CommercialOffer(
        offer_id="parcours-metier",
        label="Parcours métier",
        engine="B2C Learning",
        buyer="Individu/financeur",
        object_sold="Parcours 12 mois",
        pricing_unit="Unitaire",
        price_eur=990.0,
        variable_cost_eur=300.0,
        gross_margin_eur=690.0,
        margin_floor_pct=0.65,
        source_decision_id="ECO-007",
        notes="12 mois accès ; certification séparée.",
    ),
    CommercialOffer(
        offer_id="intensive-hybrid-week",
        label="Intensive Hybrid Week",
        engine="Cohorte",
        buyer="Individu/entreprise/institution",
        object_sold="5 jours intensifs",
        pricing_unit="Par apprenant",
        price_eur=1400.0,
        variable_cost_eur=200.0,
        gross_margin_eur=1200.0,
        margin_floor_pct=0.55,
        source_decision_id="ECO-008",
        notes="15 apprenants cible ; CA cible cohorte €21,000.",
    ),
    CommercialOffer(
        offer_id="assessment-only",
        label="Assessment Only",
        engine="Certification",
        buyer="Professionnel",
        object_sold="Évaluation indépendante",
        pricing_unit="Unitaire",
        price_eur=250.0,
        variable_cost_eur=90.0,
        gross_margin_eur=160.0,
        margin_floor_pct=0.6,
        source_decision_id="ECO-009",
        notes="Évaluation + skill report ; pas de certification Academy.",
    ),
    CommercialOffer(
        offer_id="certification-academy",
        label="Certification Academy",
        engine="Certification",
        buyer="Apprenant/pro",
        object_sold="Assessment + jury + preuve",
        pricing_unit="Unitaire",
        price_eur=390.0,
        variable_cost_eur=120.0,
        gross_margin_eur=270.0,
        margin_floor_pct=0.6,
        source_decision_id="ECO-010",
        notes="Assessment + jury/rubric + preuve ; aucune autorisation automatique.",
    ),
    CommercialOffer(
        offer_id="certification-renewal",
        label="Renouvellement certification",
        engine="Certification",
        buyer="Certifié",
        object_sold="Réévaluation",
        pricing_unit="Unitaire",
        price_eur=190.0,
        variable_cost_eur=60.0,
        gross_margin_eur=130.0,
        margin_floor_pct=0.6,
        source_decision_id="ECO-011",
        notes="Réévaluation/upgrade de version.",
    ),
    CommercialOffer(
        offer_id="b2b-team",
        label="B2B Team",
        engine="B2B",
        buyer="Entreprise",
        object_sold="10 sièges",
        pricing_unit="Annuel",
        price_eur=12000.0,
        variable_cost_eur=4200.0,
        gross_margin_eur=7800.0,
        margin_floor_pct=0.55,
        source_decision_id="ECO-012",
        notes="Jusqu'à 10 sièges ; catalogue + dashboard compétences.",
    ),
    CommercialOffer(
        offer_id="b2b-growth",
        label="B2B Growth",
        engine="B2B",
        buyer="Entreprise",
        object_sold="50 sièges",
        pricing_unit="Annuel",
        price_eur=39000.0,
        variable_cost_eur=13650.0,
        gross_margin_eur=25350.0,
        margin_floor_pct=0.55,
        source_decision_id="ECO-013",
        notes="Jusqu'à 50 sièges ; formation + assessments + reporting.",
    ),
    CommercialOffer(
        offer_id="b2b-enterprise",
        label="B2B Enterprise",
        engine="B2B",
        buyer="Entreprise",
        object_sold="100 sièges",
        pricing_unit="Annuel",
        price_eur=69000.0,
        variable_cost_eur=24150.0,
        gross_margin_eur=44850.0,
        margin_floor_pct=0.55,
        source_decision_id="ECO-014",
        notes="Jusqu'à 100 sièges ; formation + gouvernance compétences.",
    ),
    CommercialOffer(
        offer_id="b2g-pilot",
        label="B2G Pilot",
        engine="B2G",
        buyer="Institution",
        object_sold="25 apprenants",
        pricing_unit="Programme",
        price_eur=35000.0,
        variable_cost_eur=15750.0,
        gross_margin_eur=19250.0,
        margin_floor_pct=0.45,
        source_decision_id="ECO-015",
        notes="Programme institutionnel pilote.",
    ),
    CommercialOffer(
        offer_id="b2g-territory",
        label="B2G Territory",
        engine="B2G",
        buyer="Institution",
        object_sold="100 apprenants",
        pricing_unit="Programme",
        price_eur=120000.0,
        variable_cost_eur=54000.0,
        gross_margin_eur=66000.0,
        margin_floor_pct=0.45,
        source_decision_id="ECO-016",
        notes="Formation + assessment + expérience selon programme.",
    ),
    CommercialOffer(
        offer_id="b2g-large",
        label="B2G Large",
        engine="B2G",
        buyer="Institution",
        object_sold="250 apprenants",
        pricing_unit="Programme",
        price_eur=250000.0,
        variable_cost_eur=112500.0,
        gross_margin_eur=137500.0,
        margin_floor_pct=0.45,
        source_decision_id="ECO-017",
        notes="Multi-cohortes + reporting impact.",
    ),
    CommercialOffer(
        offer_id="learning-to-work-client",
        label="Learning-to-Work",
        engine="Mission Economy",
        buyer="Client/partenaire",
        object_sold="Matching + ops mission",
        pricing_unit="12% GMV min €150",
        price_eur=150.0,  # the published minimum — the real per-mission fee is 12% of GMV
        variable_cost_eur=30.0,
        gross_margin_eur=120.0,
        margin_floor_pct=0.6,
        source_decision_id="ECO-019",
        notes=(
            "Facturé au client/partenaire, 12% GMV, minimum €150. Le candidat "
            "paie €0 (ECO-018) — aucun pay-to-work. Placement permanent absent de V1 (ECO-020)."
        ),
    ),
    CommercialOffer(
        offer_id="methodology-ip-licence",
        label="Methodology/IP Licence",
        engine="Platform/IP",
        buyer="École/entreprise",
        object_sold="Licence méthode",
        pricing_unit="Annuel",
        price_eur=25000.0,
        variable_cost_eur=5000.0,
        gross_margin_eur=20000.0,
        margin_floor_pct=0.75,
        source_decision_id="ECO-021",
        notes="Phase 2.",
    ),
    CommercialOffer(
        offer_id="academy-spatial-licence",
        label="Academy+Spatial Licence",
        engine="Platform/IP",
        buyer="Institution/entreprise",
        object_sold="Licence plateforme + Spatial",
        pricing_unit="Annuel",
        price_eur=60000.0,
        variable_cost_eur=12000.0,
        gross_margin_eur=48000.0,
        margin_floor_pct=0.75,
        source_decision_id="ECO-022",
        notes="Phase 3.",
    ),
    CommercialOffer(
        offer_id="white-label-enterprise",
        label="White-label Enterprise",
        engine="Platform/IP",
        buyer="Enterprise",
        object_sold="Licence + customisation",
        pricing_unit="Annuel",
        price_eur=120000.0,
        variable_cost_eur=24000.0,
        gross_margin_eur=96000.0,
        margin_floor_pct=0.75,
        source_decision_id="ECO-023",
        notes="Phase 3. + €25,000 setup (source: Decisions_Fondateur ECO-023).",
    ),
    CommercialOffer(
        offer_id="internal-cvln-capability",
        label="Internal CVLN Capability",
        engine="Internal Value",
        buyer="Entités CVLN",
        object_sold="Qualification opérateur",
        pricing_unit="Non commercial",
        price_eur=0,
        variable_cost_eur=0,
        gross_margin_eur=0,
        margin_floor_pct=0,
        source_decision_id="ECO-024",
        notes="Jamais vendu au public ; valeur mesurée par KPI internes, hors CA commercial.",
    ),
]

POLICIES: List[EconomicPolicy] = [
    EconomicPolicy(
        policy="Accès gratuit",
        decision="Orientation uniquement",
        rule="Aucune certification, mission garantie ou contenu interne.",
    ),
    EconomicPolicy(
        policy="Paiement fractionné",
        decision="3x sans frais dès €300",
        rule="Pas de 6x en V1.",
    ),
    EconomicPolicy(
        policy="Bourses",
        decision="10% des places cohortes",
        rule="Sponsor/B2G/budget impact.",
    ),
    EconomicPolicy(
        policy="Promotions",
        decision="Pas de soldes permanentes",
        rule="Annual discount + bourses + partenariats.",
    ),
    EconomicPolicy(
        policy="Annual discount",
        decision="16.7%",
        rule="Déjà intégré aux prix annuels.",
    ),
    EconomicPolicy(
        policy="Partenaires acquisition",
        decision="15% max",
        rule="Revenu encaissé attribuable.",
    ),
    EconomicPolicy(
        policy="Réinvestissement contenu",
        decision="10% du CA",
        rule="Contenu + Spatial + assessment + qualité.",
    ),
    EconomicPolicy(
        policy="BRIDGE",
        decision="Non vendu seul",
        rule="Career/B2B/B2G/sponsor.",
    ),
    EconomicPolicy(
        policy="Cross-CVLN",
        decision="Pas de micro-cours B2C",
        rule="B2B/B2G/Enterprise/interne.",
    ),
    EconomicPolicy(
        policy="Internal restricted",
        decision="Jamais vendu",
        rule="Accès par rôle/gouvernance.",
    ),
    EconomicPolicy(
        policy="Mission fee candidat",
        decision="€0",
        rule="Aucun pay-to-work.",
    ),
    EconomicPolicy(
        policy="Mission fee client",
        decision="12% GMV min €150",
        rule="Mission/projet.",
    ),
    EconomicPolicy(
        policy="Placement permanent",
        decision="Absent V1",
        rule="Pas de fee recrutement permanent.",
    ),
    EconomicPolicy(
        policy="Qualification standard",
        decision="24 mois",
        rule="Requalification à échéance/version majeure.",
    ),
    EconomicPolicy(
        policy="Qualification sensible",
        decision="12 mois",
        rule="Cyber/finance/privileged.",
    ),
    EconomicPolicy(
        policy="Executive authority",
        decision="Jamais délivrée par Academy",
        rule="Mandat gouvernance uniquement.",
    ),
    EconomicPolicy(
        policy="Claims financements/certifications publiques",
        decision="Preuve préalable",
        rule="Aucun RNCP/CPF/éligibilité sans source vérifiée.",
    ),
    EconomicPolicy(
        policy="CVE/JCC",
        decision="Séparés du pricing public",
        rule="EUR reste unité de prix.",
    ),
]


def get_offer(offer_id: str) -> "CommercialOffer | None":
    return next((o for o in OFFERS if o.offer_id == offer_id), None)
