import { routeToTopologyNode } from "@/lib/spatial/routeTopologyMap";

/**
 * Visual environment states for the existing Spatial topology.
 *
 * App.js + routeTopologyMap.js + topology.js remain authoritative for routing.
 * This file only translates a known topology node into camera/environment
 * variables consumed by the cinematic Spatial world.
 */
export const WORLD_SCENES = Object.freeze({
  LANDING: {
    zone: "world",
    camera: "horizon",
    depth: 0,
    scale: 1,
    x: 0,
    y: 0,
    light: 1,
    focusX: 50,
    focusY: 50,
    warmth: 1,
    vignette: 0.42,
  },
  ONBOARDING: {
    zone: "gateway",
    camera: "approach",
    depth: 1,
    scale: 1.08,
    x: -3,
    y: 1,
    light: 1.04,
    focusX: 59,
    focusY: 50,
    warmth: 1.04,
    vignette: 0.48,
  },
  DASHBOARD: {
    zone: "hub",
    camera: "focus",
    depth: 2,
    scale: 1.13,
    x: 2,
    y: -1,
    light: 0.98,
    focusX: 63,
    focusY: 44,
    warmth: 0.96,
    vignette: 0.54,
  },
  FORMATIONS: {
    zone: "learning-district",
    camera: "horizon",
    depth: 2,
    scale: 1.14,
    x: 5,
    y: -1,
    light: 1.03,
    focusX: 70,
    focusY: 48,
    warmth: 1.06,
    vignette: 0.46,
  },
  FORMATION: {
    zone: "learning-destination",
    camera: "focus",
    depth: 3,
    scale: 1.21,
    x: 8,
    y: -2,
    light: 1.06,
    focusX: 74,
    focusY: 53,
    warmth: 1.08,
    vignette: 0.5,
  },
  MODULE: {
    zone: "learning-interior",
    camera: "enter",
    depth: 4,
    scale: 1.29,
    x: 11,
    y: -3,
    light: 0.87,
    focusX: 80,
    focusY: 48,
    warmth: 0.82,
    vignette: 0.68,
  },
  ROADMAP: {
    zone: "horizon-path",
    camera: "horizon",
    depth: 2,
    scale: 1.11,
    x: -6,
    y: -2,
    light: 1.08,
    focusX: 44,
    focusY: 58,
    warmth: 1.08,
    vignette: 0.46,
  },
  MISSIONS_LIST: {
    zone: "action-district",
    camera: "reveal",
    depth: 2,
    scale: 1.14,
    x: -3,
    y: 1,
    light: 0.97,
    focusX: 46,
    focusY: 52,
    warmth: 0.96,
    vignette: 0.56,
  },
  BADGES: {
    zone: "achievement",
    camera: "reveal",
    depth: 2,
    scale: 1.11,
    x: 3,
    y: 2,
    light: 1.08,
    focusX: 64,
    focusY: 48,
    warmth: 1.15,
    vignette: 0.48,
  },
  SKILLS: {
    zone: "achievement",
    camera: "focus",
    depth: 2,
    scale: 1.13,
    x: 2,
    y: 1,
    light: 1.03,
    focusX: 60,
    focusY: 46,
    warmth: 1.04,
    vignette: 0.5,
  },
  CERTIFICATIONS: {
    zone: "achievement",
    camera: "confirm",
    depth: 2,
    scale: 1.12,
    x: 4,
    y: 1,
    light: 1.1,
    focusX: 67,
    focusY: 45,
    warmth: 1.18,
    vignette: 0.46,
  },
  WALLET: {
    zone: "value",
    camera: "focus",
    depth: 2,
    scale: 1.1,
    x: -4,
    y: 1,
    light: 0.9,
    focusX: 38,
    focusY: 50,
    warmth: 0.78,
    vignette: 0.66,
  },
  FREK_PROFILE: {
    zone: "identity",
    camera: "focus",
    depth: 2,
    scale: 1.11,
    x: -2,
    y: 0,
    light: 0.96,
    focusX: 42,
    focusY: 44,
    warmth: 0.9,
    vignette: 0.6,
  },
});

export const STATIC_SCENE = Object.freeze({
  zone: "neutral",
  camera: "static",
  depth: 0,
  scale: 1,
  x: 0,
  y: 0,
  light: 0.92,
  focusX: 50,
  focusY: 50,
  warmth: 0.9,
  vignette: 0.55,
});

export function sceneForPathname(pathname) {
  const node = routeToTopologyNode(pathname);
  return {
    node,
    scene: (node && WORLD_SCENES[node]) || STATIC_SCENE,
  };
}
